const libraryFumos = [
  // Common
  { name: 'Reimu(Common)' },
  { name: 'Marisa(Common)' },
  { name: 'Cirno(Common)' },
  { name: 'Sanae(Common)' },
  // { name: 'Reisen(Common)' },
  // { name: 'Tewi(Common)' },
  // { name: 'Shion(Common)' },
  // { name: 'Renko(Common)' },
  // { name: 'Kosuzu(Common)' },
  // { name: 'Akyuu(Common)' },
  // { name: 'LilyWhite(Common)' },

  // Uncommon
  { name: 'Sakuya(UNCOMMON)' },
  { name: 'Meiling(UNCOMMON)' },
  { name: 'Patchouli(UNCOMMON)' },
  // { name: 'Momiji(UNCOMMON)' },
  // { name: 'Rumia(UNCOMMON)' },
  // { name: 'Koakuma(UNCOMMON)' },

  // Rare
  // { name: 'SillyCirno(RARE)' },
  { name: 'Remilia(RARE)' },
  { name: 'Youmu(RARE)' },
  // { name: 'Komachi(RARE)' },
  // { name: 'Chen(RARE)' },
  // { name: 'Kokoro(RARE)' },
  // { name: 'Hatate(RARE)' },
  // { name: 'Nitori(RARE)' },

  // Epic
  // { name: 'MarketableHakari!?!?(EPIC)' },
  // { name: 'LuckySanae(EPIC)' },
  { name: 'Ran(EPIC)' },
  { name: 'Satori(EPIC)' },
  { name: 'Kasen(EPIC)' },
  // { name: 'Aya(EPIC)' },
  // { name: 'Joon(EPIC)' },
  // { name: 'Miko(EPIC)' },
  // { name: 'Doremy(EPIC)' },
  // { name: 'Keine(EPIC)' },
  // { name: 'Kogasa(EPIC)' },
  { name: 'Traumatized(EPIC)' },
  { name: 'Eye-Popping(EPIC)' },
  { name: 'AbandonedChild(EPIC)' },

  // Otherworldly
  { name: 'TankReisen(OTHERWORLDLY)' },
  // { name: 'Texas(OTHERWORLDLY)' },
  // { name: 'Xinyan(OTHERWORLDLY)' },
  // { name: 'Aether(OTHERWORLDLY)' },
  // { name: 'Zhongli(OTHERWORLDLY)' },
  // { name: 'Amber(OTHERWORLDLY)' },
  // { name: 'Rosaria(OTHERWORLDLY)' },
  // { name: 'May(OTHERWORLDLY)' },
  // { name: 'Monika(OTHERWORLDLY)' },
  { name: 'Bocchi(OTHERWORLDLY)' },
  { name: 'Faruzamn(OTHERWORLDLY)' },
  { name: 'Cloaker(OTHERWORLDLY)' },

  // Legendary
  // { name: 'Junko,realperson(LEGENDARY)' },
  // { name: 'BathRan(LEGENDARY)' },
  { name: 'Flandere(LEGENDARY)' },
  { name: 'Yukari(LEGENDARY)' },
  { name: 'Yuyuko(LEGENDARY)' },
  // { name: 'Eiki(LEGENDARY)' },
  // { name: 'Suwako(LEGENDARY)' },
  // { name: 'Kaguya(LEGENDARY)' },
  // { name: 'Mokou(LEGENDARY)' },
  // { name: 'Koishi(LEGENDARY)' },
  // { name: 'Suika(LEGENDARY)' },
  // { name: 'Byakuren(LEGENDARY)' },
  // { name: 'Kanako(LEGENDARY)' },
  // { name: 'Iku(LEGENDARY)' },
  // { name: 'Urumi(LEGENDARY)' },
  // { name: 'Keiki(LEGENDARY)' },
  // { name: 'Utsuho(LEGENDARY)' },
  // { name: 'Sagume(LEGENDARY)' },
  // { name: 'Oirin(LEGENDARY)' },
  { name: 'ExplodedMan(LEGENDARY)' },
  { name: 'Gambler(LEGENDARY)' },

  // Mythical
  // { name: 'Gojo(MYTHICAL)' },
  // { name: 'CupOfRemilia(MYTHICAL)' },
  // { name: 'YaeMiko(MYTHICAL)' },
  { name: 'Junko(MYTHICAL)' },
  { name: 'Tenshi(MYTHICAL)' },
  { name: 'Yuuka(MYTHICAL)' },
  { name: 'Eirin(MYTHICAL)' },
  // { name: 'Okina(MYTHICAL)' },
  // { name: 'Momoyi(MYTHICAL)' },
  // { name: 'TheDualFumo(MYTHICAL)' },
  { name: 'MonkeyLeader(MYTHICAL)' },
  { name: 'OneShotCurse(MYTHICAL)' },
  { name: 'AvoidChildSupport(MYTHICAL)' },

  // Exclusive
  { name: 'BlueReimu(EXCLUSIVE)' },
  { name: 'RedMarisa(EXCLUSIVE)' },
  { name: 'DarkYoumu(EXCLUSIVE)' },
  { name: 'CirnoSitting(EXCLUSIVE)' },
  { name: 'HyperSakuya(EXCLUSIVE)' },
  // { name: 'Furina(EXCLUSIVE)' },
  // { name: 'HyperFlandere(EXCLUSIVE)' },
  // { name: 'HyperYoumu(EXCLUSIVE)' },
  // { name: 'GamingReimu(EXCLUSIVE)' },
  // { name: 'MarketableDon(EXCLUSIVE)' },
  // { name: 'MarketableBobo(EXCLUSIVE)' },
  // { name: 'Ishmael(EXCLUSIVE)' },
  // { name: 'Shiroko(EXCLUSIVE)' },
  // { name: 'Amiya(EXCLUSIVE)' },

  // ???
  { name: 'Go/jo(???)' },
  { name: 'Fraudkuna(???)' },
  { name: 'SkibidiToilet(???)' },
  { name: 'GawrGura(???)' },
  // { name: 'MarketableHutao(???)' },
  // { name: 'Gebura(???)' },
  { name: 'Miku(???)' },
  { name: 'Rin(???)' },
  { name: 'Miku-Senbonzakura,version(???)' },
  { name: 'ImSorryOfficerFumo(???)' },
  // { name: 'FrostNova(???)' },
  // { name: 'Serika(???)' },
  // { name: 'Penance(???)' },
  // { name: 'WarCrimeReimu(???)' },

  // Astral
  { name: 'Athena(ASTRAL)' },
  // { name: 'TheClaw-LoR(ASTRAL)' },
  // { name: 'UltraKillV1(ASTRAL)' },
  // { name: 'Yukari-RinnosukeVer(ASTRAL)' },
  // { name: 'Patchouli-RinnosukeVer(ASTRAL)' },
  // { name: 'Noshiro(ASTRAL)' },
  // { name: 'Shinano(ASTRAL)' },
  // { name: 'LeMalin(ASTRAL)' },
  // { name: 'Formidable(ASTRAL)' },
  { name: 'Cheshire(ASTRAL)' },

  // Infinite
  { name: 'Mima(INFINITE)' },
  // { name: 'PC-98Reimu(INFINITE)' },
  // { name: 'PC-98Marisa(INFINITE)' },
  // { name: 'Sans(INFINITE)' },

  // Celestial
  { name: 'Mostima(CELESTIAL)' },
  { name: 'Grani(CELESTIAL)' },

  // Eternal
  { name: 'UltraKillV2(ETERNAL)' },
  // { name: 'TheBugAbuser(ETERNAL)' },
  // { name: 'TheIntrovertedOne(ETERNAL)' },
  // { name: 'TheGermanMan-BoboVer(ETERNAL)' },
  // { name: 'Flandere-VampirePursingTheHunter(ETERNAL)' },
  // { name: 'Remilia-TinyDevilMansion(ETERNAL)' },
  // { name: 'PlushieFlandere?-TouhouLostwordVer(ETERNAL)' },

  // Transcendent
  { name: 'Arisu(TRANSCENDENT)' },
  // { name: 'MarketableMaomao(TRANSCENDENT)' },
  // { name: 'MarketableJinshi(TRANSCENDENT)' },
  { name: 'TheOwner(TRANSCENDENT)' },
  { name: 'Rinnosuke(TRANSCENDENT)' },
  { name: 'HeianSukuna(TRANSCENDENT)' },
];

module.exports = libraryFumos;